name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - uses: actions/setup-python@v5.1.0
      - uses: psf/black@24.4.2
        with:
          args: ". --check"
